file_format: "1"
id: izmir
name: izmir
type: shield
url: https://github.com/ozkan/izmir
requires:
  - pro_micro
outputs:
  - usb
  - ble
features:
  - keys
  - underglow
  - encoder 
  - studio
siblings:
  - izmir_left
  - izmir_right
